---
title: "Motivation Barometer & THRIVE"
format:
  html:
    toc: true
    toc-depth: 2
    page-layout: full
    smooth-scroll: true
---

## About this dataset

The Motivation Barometer & THRIVE dataset brings together both (sequential) **cross-sectional as repeated follow-up** surveys with a large panel of participants in Belgium. It follows people’s motivation, psychological functioning, and societal attitudes during and after the COVID-19 crisis and across broader societal challenges.

- All variables with items can be found in the [codebook](codebook.qmd)
- A total overview of variables can be found [here](#total-overview-of-variables)
- See all variables by follow-up survey [here](#variables-by-follow-up-survey)

## Total overview of variables

This is a list of all variables and information included in the total dataset (including both cross-sectional as longitudinal assessments). To see the list of variables included in longitudinal follow-up surveys, click [here](#variables-by-year)

### 1. Core psychological processes

- **Basic Psychological Needs**
  - Autonomy (satisfaction and frustration)
  - Competence (satisfaction and frustration)
  - Relatedness (satisfaction and frustration)

- **Motivation**
  - **_Adherence to the measures_**
    - Identified motivation
    - Introjected motivation
    - External motivation
    - Amotivation
    - Effort
    - Reactance
  - **_Vaccination_**
    - Identified motivation
    - External motivation
    - Amotivation (defiance)
    - Amotivation (distrust)
    - Amotivation (self-efficacy)
  - **_Measures-specific_**: face covering, hand washing, taking pcr test, physical distance, quarantaine, social distancing, ventilation
  - **_Outcome expectation_**: physical distance, hand washing, face covering, pcr test, social contact, telework, ventilatino (self and population) 
  - **_Self-efficacy_**: physical distance, hand washing, face covering, pcr test, social contact, telework, ventilatino (duration and effort)

- **Well-being and Ill-being**
  - Life satisfaction
  - Vitality and depletion
  - Mindfulness
  - Emotion-Regulation
  - Novelty
  - Sleep duration
  - Anxiety and Depression
  - Aspiration (importance and in practice, post-crisis)
  - Boredom
  - Climate anxiety
  - Concerns: health, significant others, situation, finances, job, climate change, war, new COVID-19 variants
  - Loneliness
  - Parental stress

### 2. Behavior and behavioral intentions

- **Behavior**
  - Adherence to the measures (keeping physical distance, hand washing, avoiding social contect, wearing mouthmask, working from home, ventilation)
  - Planned adherence
  - Taking part in a protest

- **Intention to climate activism**

### 3. Perceptions of crisis and society

- **Risk perception** 
  - COVID-19: perceived infection chance and severity of symptoms (towards self and population)
  - future crises: perceived infection chance and severity of symptoms (towards self and population)

- **Trust**
  - how competence one is perceived to be (celebrities, doctors, experts, nurses, healthcare, pharmacists, politicans)
  - trust and perceived expertise with doctor, expert, media, pharmacist, politicians, other vaccinated persons

- **Societal themes**
  - populism
  - anomie
  - autocratic versus democratic attitudes

- **Perception of how the crisis is handled by the policy**

- **Evaluation of: the measures, obligated vaccination**

- **Memories** of the COVID-19 crisis

- **Future crisis**
  - approach
  - preparedness  

- **Conspiracy theories**
  - On corona
  - General

- **Communication style**
  - Autonomy-supportive (Participative, Attuning)
  - Structure (Guiding, Clarifying)
  - Controlling (Demanding, Domineering)
  - Chaos (Abandoning, Awaiting)

### 4. Contextual and background variables

- **Meta**
  - Date
  - Weather (daily temperature, sun duration, humidity)
  - Google Mobility data
  - Holiday periods
  - Season

- **Sociodemographics**
  - age
  - civil status
  - comorbidities
  - infection/hospitalization status
  - education level
  - financial situation
  - gender
  - language
  - physical activity
  - province of living
  - religion
  - socio-economic status
  - work situation

- **Crisis-related information**
  - Infections: raw numbers, incremental value (source: Sciensano)
  - Hospitalizations: raw numbers, incremental value (source: Sciensano)
  - Mortalities: raw numbers, incremental value (source: Sciensano)
  - Number of vaccination doses (A - EEE, source: Sciensano)
  - Stringency Index (source: Oxford Govermental Tool)
  
## Variables by follow-up survey

::: {.callout-note collapse="true" appearance="simple"}
## 2025: Post-crisis adjustment & regimes

### Core battery:

- **Memory** about COVID-19 crisis  

- **Trust**  
  Populism  
  Trust towards politicians, healthcare workers, social media, traditional media, scientists  
  Conspiracy beliefs

- **Basic psychological needs**  
  Autonomy, competence, and relatedness satisfaction, unfulfillment and frustration  
  Perceived support and thwart in life

- **Well-being and ill-being**  
  Anxiety, depression, depletion  
  Vitality & life satisfaction  
  Sleep quality  
  Concerns
  
### Specific modules

- **Youth images**  
  Both in perspective of general youth as own child (younger than 25)

- **Post crisis**  
  Identity development and post-traumatic growth

- **Capabilities**  

- **Governmental communication style**  
  The development of a circumplex pattern
  
- **Old and new crises**  
  Intention to adhere to COVID-19 and climate-related measures and related (lack of) motivation  
  Risk perception COVID-19, climate crisis and societal crisis in general. 
  Intented usage of COVID-19 hygiene behaviors at work and at family occassions when feeling sick

---

See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd)

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2024: Post-crisis adjustment & regimes

### Core battery:

- **Memory** about COVID-19 crisis  

- **Trust**  
  Populism  
  Trust towards politicians, healthcare workers, social media, traditional media, scientists  
  Conspiracy beliefs

- **Basic psychological needs**  
  Autonomy, competence, and relatedness satisfaction and frustration  
  Group-based needs 

- **Well-being and ill-being**  
  Anxiety, depression, depletion  
  Vitality & life satisfaction  
  Sleep quality  
  Concerns  
  Flourishing/mental health (MHC)  
  self-compassion  

- **Post crisis**  
  Identity development and post-traumatic growth

### Specific modules:

- **Democratic attitudes and societal views**  
  Perceptions of democracy and autocracy, anomie, populist attitudes, conspiracy beliefs (incl. corona), views on experts and government.

- **Information sources & communication**  
  Use of information sources, following governmental communication (e.g., press conferences).

- **Social identities & group membership**  
  Identity centrality, national and government identification, social group variables.

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2022: COVID transition period, climate concern & vaccination attitudes

- **Crisis perceptions & societal attitudes**  
  Attitudes toward **obligatory vaccination**  
  Perceived risk (general)  
  Climate anxiety and climate-related worry  
  Intention toward climate activism  

- **Vaccination behaviour, intentions & motivation**  
  Vaccination status (dose count: 1–4 doses, one/two doses)  
  Intention for yearly booster  
  Beliefs about vaccine efficacy & safety
  Motivation for vaccination (SDT-based): External motivation, Identified motivation, Amotivation (defiance, distrust, self-efficacy)  

- **Perceptions of experts, government & institutions**  
  Trust in experts and government  
  Perceived competence, integrity, benevolence of authorities  

- **Behaviour when symptomatic**  
  Protective behaviour and adherence  
  (e.g., avoiding interactions, mask use, informing others)

- **Basic psychological needs**  
  Autonomy, competence, and relatedness satisfaction and frustration  
  Group-based needs 

- **Well-being and ill-being**  
  Anxiety, depression, depletion  
  Vitality & life satisfaction  
  Sleep quality  
  Concerns  

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2022: Post-COVID

[to be updated]

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2021: December

[to be updated]

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2021: COVID wave III

[to be updated]

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2020: December

[to be updated]

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2020: COVID wave II

[to be updated]

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

::: {.callout-note collapse="true" appearance="simple"}
## 2020: COVID wave I

[to be updated]

---

<!-- See overview of responses in [Follow-Up 2025 dashboard](dashboards/FU2025.qmd) -->

See overview of longitudinal responses in [Longitudinal dashboard](dashboards/Longitudinal.qmd)

:::

